# Generated by Django 4.1.4 on 2022-12-30 22:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('number_of_members', models.PositiveBigIntegerField()),
                ('slogan', django_quill.fields.QuillField()),
                ('rules', django_quill.fields.QuillField()),
            ],
        ),
    ]
